INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('1', '4', '3', '2019-02-20 04:05:57', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('2', '2', '3', '2019-02-20 01:31:28', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('3', '3', '4', '2019-02-20 01:43:14', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('4', '2', '3', '2019-02-20 03:00:27', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('5', '1', '1', '2019-02-20 03:33:03', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('6', '2', '1', '2019-02-20 02:41:40', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('7', '2', '2', '2019-02-20 02:05:43', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('8', '4', '2', '2019-02-20 03:37:07', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('9', '2', '3', '2019-02-20 03:41:01', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('10', '1', '3', '2019-02-20 03:53:37', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('1', '4', '1', '2019-02-20 04:42:08', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('2', '3', '2', '2019-02-20 03:53:25', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('3', '2', '2', '2019-02-20 01:46:29', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('4', '3', '1', '2019-02-20 01:45:21', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('5', '1', '1', '2019-02-20 02:15:32', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('6', '2', '2', '2019-02-20 03:04:27', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('7', '3', '4', '2019-02-20 02:37:53', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('8', '2', '1', '2019-02-20 02:05:26', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('9', '1', '3', '2019-02-20 03:22:41', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('10', '4', '4', '2019-02-20 04:48:57', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('1', '1', '3', '2019-02-20 01:53:58', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('2', '1', '4', '2019-02-20 02:25:52', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('3', '3', '2', '2019-02-20 01:49:47', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('4', '2', '3', '2019-02-20 03:04:11', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('5', '2', '1', '2019-02-20 02:54:55', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('6', '3', '3', '2019-02-20 04:07:26', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('7', '4', '4', '2019-02-20 02:21:28', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('8', '3', '3', '2019-02-20 04:25:58', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('9', '2', '1', '2019-02-20 02:37:38', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('10', '2', '3', '2019-02-20 03:39:23', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('1', '3', '1', '2019-02-20 02:12:09', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('2', '1', '1', '2019-02-20 03:41:11', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('3', '2', '1', '2019-02-20 02:43:55', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('4', '3', '4', '2019-02-20 04:31:52', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('5', '2', '3', '2019-02-20 01:59:36', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('6', '3', '3', '2019-02-20 02:24:43', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('7', '2', '3', '2019-02-20 03:14:54', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('8', '4', '3', '2019-02-20 04:03:44', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('9', '4', '4', '2019-02-20 04:28:34', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('10', '1', '1', '2019-02-20 02:09:06', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('1', '2', '3', '2019-02-20 03:07:57', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('2', '2', '2', '2019-02-20 02:00:34', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('3', '2', '2', '2019-02-20 04:37:46', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('4', '2', '4', '2019-02-20 04:13:51', True);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('5', '4', '3', '2019-02-20 02:52:07', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('6', '4', '2', '2019-02-20 01:58:48', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('7', '3', '2', '2019-02-20 02:01:53', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('8', '4', '3', '2019-02-20 03:13:24', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('9', '2', '2', '2019-02-20 02:31:15', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
INSERT INTO oc_dapython_pr6.commande (client_id, boutique_id, paiement_type_id, date, paiement) VALUES ('10', '1', '2', '2019-02-20 02:50:21', False);
SET @NewCommande = (SELECT MAX(id) FROM oc_dapython_pr6.commande);
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '2');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '3');
INSERT INTO `oc_dapython_pr6`.`commande_composition` (`commande_id`, `recette_id`) VALUES (@NewCommande, '1');
