@startuml 08_diagram_component
title Diagramme de composants

node Django {
    [Authentification]
    [Commande]
    [Boutique]
    [Recette]
}
database Postgres {
    [OC Pizza DB]
}

node Banque <<composant externe>> {
    [API de paiement]
}

[Commande] -- () "Validation paiement"
() "Validation paiement" -- [API de paiement]

[OC Pizza DB] -- () "Gestion des données"
() "Gestion des données" -- Django

[Boutique] - [Recette]
[Authentification] - [Commande]
[Boutique] -- [Authentification]
[Recette] -- [Commande]
[Boutique] -- [Commande]

@enduml