@startuml 09_diagram_deployment
title Diagramme de déploiement


node "appareil utilisateur"{
    [navigateur web]
}

cloud {
    rectangle "Amazon Web Service"{
        node gunicorn {
            ["App Django"]
        }
        node Nginx{
            ["Données statiques"]
        }
        database "Postgres"{
        ["OC Pizza Database"]
    }
    
}
}
cloud {
    [Banque API]
}

[navigateur web] -> ["App Django"] : "           HTTPS           "

[navigateur web] --> [Banque API] : "HTTPS"

["App Django"] -- [Banque API] : "TCP/IP"

["App Django"] -up- ["OC Pizza Database"] : TCP/IP"

["App Django"] - ["Données statiques"]: "       TCP/IP"

@enduml